version: "3.8"

services:
  portfolio:
    container_name: portfolio
    image: longvu2907/portfolio
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
